---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: centos-5.10
    driver_config:
      box: centos-5.10
      box_url: https://s3-us-west-2.amazonaws.com/nmd-centos-vmware/opscode_centos-5.10_chef-latest-latest.box
suites:
  - name: default
    run_list:
      - recipe[nmdvarnish::default]
    #data_bags_path: /home/davidxarnold/highwire/chef/data_bags
    data_bags_path: "<%= ENV['NMDVARNISH_DATA_BAGS_PATH'] %>"
    attributes: {
        'nmdvarnish': {
          'sites': {
            'default': {
              'acladdresses': [
                '"127.0.0.1"/32',
                '"127.1.1.1"/32'
              ]
            },
            'example2': {
              'acladdresses':
                ['"127.0.1.1"/32']
              }
          }
        }
      }
