---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: centos-5.10
    driver_config:
      box: centos-5.10
      # box_url: https://nmd-virtualbox.s3-us-west-2.amazonaws.com/nmd-ubunutu-12.04-i386-base-latest.box
      box_url: https://nmd-virtualbox.s3-us-west-2.amazonaws.com/nmd-ubunutu-12.04-i386-base-latest.box
suites:
  - name: default
    run_list:
      - recipe[nmdvarnish::default]
    attributes:
