# encoding: utf-8
require 'chefspec'
require 'spec_helper'

describe 'nmdvarnish::default' do
  let(:chef_run) { ChefSpec::Runner.new.converge(described_recipe) }

  it 'Installs the varnish package.' do
    expect(chef_run).to install_package('varnish')
  end
  it 'Configures varnish.' do
    expect(chef_run).to create_template('/etc/default/varnish').with(
      user: 'root',
      group: 'root',
      mode: 0644
    )
    expect(chef_run).to render_file('/etc/default/varnish')
      .with_content(/^# This file was generated by Chef for*.+$/)

    expect(chef_run).to render_file('/etc/default/varnish')
      .with_content(/^# Do NOT modify this file by hand!$/)

    expect(chef_run).to render_file('/etc/default/varnish')
      .with_content(/^START=(yes|no)$/)

    expect(chef_run).to render_file('/etc/default/varnish')
      .with_content(/^NFILES=\d*$/)

    expect(chef_run).to render_file('/etc/default/varnish')
      .with_content(/^MEMLOCK=\d*$/)

    expect(chef_run).to render_file('/etc/default/varnish')
      .with_content(/^INSTANCE=/)

    expect(chef_run).to render_file('/etc/default/varnish')
      .with_content(/^DAEMON_OPTS=/)

  end
end
